name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _r-mutex=1.0.0
  - alabaster=0.7.12
  - anaconda=2021.11
  - anaconda-client=1.9.0
  - anaconda-navigator=2.4.2
  - anaconda-project=0.10.1
  - anyio=2.2.0
  - appdirs=1.4.4
  - applaunchservices=0.2.1
  - appnope=0.1.2
  - appscript=1.1.2
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - asn1crypto=1.4.0
  - astor=0.8.1
  - astroid=2.6.6
  - astropy=4.3.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.7
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - bitarray=2.3.0
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - blosc=1.21.0
  - bokeh=2.4.1
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.14.0
  - conda-build=3.21.5
  - conda-content-trust=0.1.1
  - conda-env=2.6.0
  - conda-pack=0.8.1
  - conda-package-handling=1.7.3
  - conda-repo-cli=1.0.4
  - conda-token=0.3.0
  - conda-verify=3.4.2
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=3.4.8
  - curl=7.78.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dal=2021.3.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2021.10.0
  - docutils=0.17.1
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - fastcache=1.1.0
  - filelock=3.3.1
  - flake8=3.9.2
  - flask=1.1.2
  - fonttools=4.25.0
  - formulaic=0.3.4
  - freetype=2.10.4
  - fsspec=2021.8.1
  - future=1.0.0
  - get_terminal_size=1.0.0
  - gevent=21.8.0
  - giflib=5.2.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.0.8
  - greenlet=1.1.1
  - gsl=2.7.1
  - hdf5=1.10.6
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=3.2
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - interface_meta=1.3.0
  - intervaltree=3.1.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.0
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=23.1.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcurl=7.78.0
  - libcxx=12.0.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc=4.8.5
  - libgfortran=3.0.1
  - libiconv=1.16
  - liblief=0.10.1
  - libllvm11=11.1.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - linearmodels=4.27
  - llvm-openmp=12.0.0
  - llvmlite=0.37.0
  - locket=0.2.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - more-itertools=8.10.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - navigator-updater=0.2.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - networkx=2.6.3
  - nltk=3.6.5
  - nose=1.3.7
  - notebook=6.4.5
  - numba=0.54.1
  - numexpr=2.7.3
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - pandocfilters=1.4.3
  - parso=0.8.2
  - partd=1.2.0
  - path=16.0.0
  - path.py=12.5.0
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pkginfo=1.7.1
  - pluggy=0.13.1
  - ply=3.11
  - poyo=0.5.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - property-cached=1.6.4
  - property_cached=1.6.4
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.44.1
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pyhdfe=0.2.0
  - pyjwt=2.10.1
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyodbc=4.0.31
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python.app=3
  - python_abi=3.9
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyyaml=6.0
  - pyzmq=22.2.1
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - r-assertthat=0.1
  - r-base=3.3.1
  - r-base64enc=0.1_3
  - r-bh=1.60.0_2
  - r-bitops=1.0_6
  - r-boot=1.3_18
  - r-car=2.1_2
  - r-caret=6.0_70
  - r-catools=1.17.1
  - r-chron=2.3_47
  - r-class=7.3_14
  - r-cluster=2.0.4
  - r-codetools=0.2_14
  - r-colorspace=1.2_6
  - r-crayon=1.3.1
  - r-curl=0.9.7
  - r-data.table=1.9.6
  - r-dbi=0.4_1
  - r-dichromat=2.0_0
  - r-digest=0.6.9
  - r-dplyr=0.4.3
  - r-essentials=1.4.3
  - r-evaluate=0.9
  - r-foreach=1.4.3
  - r-foreign=0.8_66
  - r-formatr=1.4
  - r-ggplot2=2.1.0
  - r-gistr=0.3.6
  - r-glmnet=2.0_5
  - r-gtable=0.2.0
  - r-hexbin=1.27.1
  - r-highr=0.6
  - r-htmltools=0.3.5
  - r-htmlwidgets=0.6
  - r-httpuv=1.3.3
  - r-httr=1.2.0
  - r-irdisplay=0.4.3
  - r-irkernel=0.7
  - r-iterators=1.0.8
  - r-jsonlite=0.9.22
  - r-kernsmooth=2.23_15
  - r-knitr=1.13
  - r-labeling=0.3
  - r-lattice=0.20_33
  - r-lazyeval=0.2.0
  - r-lme4=1.1_12
  - r-magrittr=1.5
  - r-maps=3.1.0
  - r-markdown=0.7.7
  - r-mass=7.3_45
  - r-matrix=1.2_6
  - r-matrixmodels=0.4_1
  - r-memoise=1.0.0
  - r-mgcv=1.8_12
  - r-mime=0.4
  - r-minqa=1.2.4
  - r-munsell=0.4.3
  - r-nlme=3.1_128
  - r-nloptr=1.0.4
  - r-nnet=7.3_12
  - r-openssl=0.9.4
  - r-pbdzmq=0.2_3
  - r-pbkrtest=0.4_6
  - r-plyr=1.8.4
  - r-pryr=0.1.2
  - r-quantmod=0.4_5
  - r-quantreg=5.26
  - r-r6=2.1.2
  - r-randomforest=4.6_12
  - r-rbokeh=0.4.2
  - r-rcolorbrewer=1.1_2
  - r-rcpp=0.12.5
  - r-rcppeigen=0.3.2.8.1
  - r-recommended=3.3.1
  - r-repr=0.7
  - r-reshape2=1.4.1
  - r-rmarkdown=0.9.6
  - r-rpart=4.1_10
  - r-scales=0.4.0
  - r-shiny=0.13.2
  - r-sparsem=1.7
  - r-spatial=7.3_11
  - r-stringi=1.1.1
  - r-stringr=1.0.0
  - r-survival=2.39_4
  - r-tibble=1.0
  - r-tidyr=0.5.1
  - r-ttr=0.23_1
  - r-uuid=0.1_2
  - r-xtable=1.8_2
  - r-xts=0.9_7
  - r-yaml=2.1.13
  - r-zoo=1.7_13
  - readline=8.1
  - regex=2021.8.3
  - requests=2.26.0
  - ripgrep=12.1.1
  - rope=0.19.0
  - rstudio=1.0.44
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.3.0
  - send2trash=1.8.0
  - setuptools=58.0.4
  - setuptools-scm=6.4.2
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.2.1
  - sphinx=4.2.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - sympy=1.9
  - tbb=2021.4.0
  - tbb4py=2021.4.0
  - tblib=1.7.0
  - terminado=0.9.4
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typed-ast=1.4.3
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - unixodbc=2.3.9
  - urllib3=1.26.7
  - watchdog=2.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.0
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=2.1.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.1
  - xlwings=0.24.9
  - xlwt=1.3.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - absl-py==2.3.1
    - astunparse==1.6.3
    - boto3==1.23.7
    - botocore==1.26.7
    - contourpy==1.3.0
    - cython==3.2.1
    - flatbuffers==25.2.10
    - gast==0.6.0
    - ghp-import==2.1.0
    - google-pasta==0.2.0
    - grpcio==1.74.0
    - h5py==3.14.0
    - importlib-resources==6.5.2
    - jmespath==1.0.0
    - keras==3.10.0
    - libclang==18.1.1
    - markdown==3.8.2
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - missingno==0.5.2
    - missingpy==0.2.0
    - ml-dtypes==0.3.2
    - namex==0.1.0
    - narwhals==2.12.0
    - numpy==1.26.4
    - openpyxl==3.1.5
    - opt-einsum==3.4.0
    - optree==0.17.0
    - packaging==25.0
    - pandas==2.3.2
    - patsy==1.0.1
    - protobuf==4.25.8
    - py4j==0.10.9.7
    - pyarrow==8.0.0
    - pygments==2.19.2
    - pyspark==3.5.3
    - rich==14.1.0
    - ruptures==1.1.9
    - s3transfer==0.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - statsmodels==0.14.5
    - tabulate==0.9.0
    - tensorboard==2.16.2
    - tensorboard-data-server==0.7.2
    - tensorflow==2.16.2
    - tensorflow-io-gcs-filesystem==0.37.1
    - termcolor==3.1.0
    - tomli==2.3.0
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - wbgapi==1.0.12
    - xgboost==2.1.4
prefix: /Users/ricardoortiz/opt/anaconda3
